<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="server\**\*.cs" />
    <Compile Remove="tests\**\*.cs" />
    <Compile Remove="launcher\**\*.cs" />
    <Compile Remove="Mithara.Web\**\*.cs" />
    <Compile Remove="launcher\**\*" />
    <Content Remove="server\**\*" />
    <Content Remove="tests\**\*" />
    <Content Remove="launcher\**\*" />
    <Content Remove="Mithara.Web\**\*" />
    <EmbeddedResource Remove="server\**\*" />
    <EmbeddedResource Remove="tests\**\*" />
    <EmbeddedResource Remove="launcher\**\*" />
    <EmbeddedResource Remove="Mithara.Web\**\*" />
    <None Remove="server\**\*" />
    <None Remove="tests\**\*" />
    <None Remove="launcher\**\*" />
    <None Remove="Mithara.Web\**\*" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LiteNetLib" Version="2.1.4" />
  </ItemGroup>
</Project>
