<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MitharaLauncher</AssemblyName>
    <RootNamespace>Mithara.Launcher</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>assets\mithara_launcher_icon.ico</ApplicationIcon>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <RuntimeFrameworkVersion>8.0.25</RuntimeFrameworkVersion>
    <TargetLatestRuntimePatch>false</TargetLatestRuntimePatch>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="assets\mithara_launcher_background.png" LogicalName="MitharaLauncherBackground.png" />
  </ItemGroup>
</Project>
