// AUTO-GENERATED - NÃO EDITAR MANUALMENTE
// Gerado em 2026-06-21 22:44:35
partial class ItemDatabase
{
    private static readonly string[] _fallbackPaths = new[]
    {
    "res://Itens/Armaduras/Leves/Botas/300008-Passos do Despertar-Normal.tres",
    "res://Itens/Armaduras/Leves/Botas/300009-Passos do Despertar-Elite.tres",
    "res://Itens/Armaduras/Leves/Botas/300020-Passos de Bruma Baixa-Normal.tres",
    "res://Itens/Armaduras/Leves/Botas/300021-Passos de Bruma Baixa-Elite.tres",
    "res://Itens/Armaduras/Leves/Botas/300032-Passos de Valebosque-Normal.tres",
    "res://Itens/Armaduras/Leves/Botas/300033-Passos de Valebosque-Elite.tres",
    "res://Itens/Armaduras/Leves/Botas/300044-Passos da Vigília Cinzenta-Normal.tres",
    "res://Itens/Armaduras/Leves/Botas/300045-Passos da Vigília Cinzenta-Elite.tres",
    "res://Itens/Armaduras/Leves/Botas/300056-Passos de Pedraforte-Normal.tres",
    "res://Itens/Armaduras/Leves/Botas/300057-Passos de Pedraforte-Elite.tres",
    "res://Itens/Armaduras/Leves/Botas/300068-Passos da Aurora Partida-Normal.tres",
    "res://Itens/Armaduras/Leves/Botas/300069-Passos da Aurora Partida-Elite.tres",
    "res://Itens/Armaduras/Leves/Botas/300080-Passos de Umbra Alta-Normal.tres",
    "res://Itens/Armaduras/Leves/Botas/300081-Passos de Umbra Alta-Elite.tres",
    "res://Itens/Armaduras/Leves/Botas/300092-Passos do Juramento Antigo-Normal.tres",
    "res://Itens/Armaduras/Leves/Botas/300093-Passos do Juramento Antigo-Elite.tres",
    "res://Itens/Armaduras/Leves/Botas/300104-Passos de Aço Estelar-Normal.tres",
    "res://Itens/Armaduras/Leves/Botas/300105-Passos de Aço Estelar-Elite.tres",
    "res://Itens/Armaduras/Leves/Botas/300116-Passos do Eclipse de Mitthara-Normal.tres",
    "res://Itens/Armaduras/Leves/Botas/300117-Passos do Eclipse de Mitthara-Elite.tres",
    "res://Itens/Armaduras/Leves/Botas/300128-Passos da Ascensão-Normal.tres",
    "res://Itens/Armaduras/Leves/Botas/300129-Passos da Ascensão-Elite.tres",
    "res://Itens/Armaduras/Leves/Calcas/300004-Calças do Despertar-Normal.tres",
    "res://Itens/Armaduras/Leves/Calcas/300005-Calças do Despertar-Elite.tres",
    "res://Itens/Armaduras/Leves/Calcas/300016-Calças de Bruma Baixa-Normal.tres",
    "res://Itens/Armaduras/Leves/Calcas/300017-Calças de Bruma Baixa-Elite.tres",
    "res://Itens/Armaduras/Leves/Calcas/300028-Calças de Valebosque-Normal.tres",
    "res://Itens/Armaduras/Leves/Calcas/300029-Calças de Valebosque-Elite.tres",
    "res://Itens/Armaduras/Leves/Calcas/300040-Calças da Vigília Cinzenta-Normal.tres",
    "res://Itens/Armaduras/Leves/Calcas/300041-Calças da Vigília Cinzenta-Elite.tres",
    "res://Itens/Armaduras/Leves/Calcas/300052-Calças de Pedraforte-Normal.tres",
    "res://Itens/Armaduras/Leves/Calcas/300053-Calças de Pedraforte-Elite.tres",
    "res://Itens/Armaduras/Leves/Calcas/300064-Calças da Aurora Partida-Normal.tres",
    "res://Itens/Armaduras/Leves/Calcas/300065-Calças da Aurora Partida-Elite.tres",
    "res://Itens/Armaduras/Leves/Calcas/300076-Calças de Umbra Alta-Normal.tres",
    "res://Itens/Armaduras/Leves/Calcas/300077-Calças de Umbra Alta-Elite.tres",
    "res://Itens/Armaduras/Leves/Calcas/300088-Calças do Juramento Antigo-Normal.tres",
    "res://Itens/Armaduras/Leves/Calcas/300089-Calças do Juramento Antigo-Elite.tres",
    "res://Itens/Armaduras/Leves/Calcas/300100-Calças de Aço Estelar-Normal.tres",
    "res://Itens/Armaduras/Leves/Calcas/300101-Calças de Aço Estelar-Elite.tres",
    "res://Itens/Armaduras/Leves/Calcas/300112-Calças do Eclipse de Mitthara-Normal.tres",
    "res://Itens/Armaduras/Leves/Calcas/300113-Calças do Eclipse de Mitthara-Elite.tres",
    "res://Itens/Armaduras/Leves/Calcas/300124-Calças da Ascensão-Normal.tres",
    "res://Itens/Armaduras/Leves/Calcas/300125-Calças da Ascensão-Elite.tres",
    "res://Itens/Armaduras/Leves/Capacetes/300000-Véu do Despertar-Normal.tres",
    "res://Itens/Armaduras/Leves/Capacetes/300001-Véu do Despertar-Elite.tres",
    "res://Itens/Armaduras/Leves/Capacetes/300012-Véu de Bruma Baixa-Normal.tres",
    "res://Itens/Armaduras/Leves/Capacetes/300013-Véu de Bruma Baixa-Elite.tres",
    "res://Itens/Armaduras/Leves/Capacetes/300024-Véu de Valebosque-Normal.tres",
    "res://Itens/Armaduras/Leves/Capacetes/300025-Véu de Valebosque-Elite.tres",
    "res://Itens/Armaduras/Leves/Capacetes/300036-Véu da Vigília Cinzenta-Normal.tres",
    "res://Itens/Armaduras/Leves/Capacetes/300037-Véu da Vigília Cinzenta-Elite.tres",
    "res://Itens/Armaduras/Leves/Capacetes/300048-Véu de Pedraforte-Normal.tres",
    "res://Itens/Armaduras/Leves/Capacetes/300049-Véu de Pedraforte-Elite.tres",
    "res://Itens/Armaduras/Leves/Capacetes/300060-Véu da Aurora Partida-Normal.tres",
    "res://Itens/Armaduras/Leves/Capacetes/300061-Véu da Aurora Partida-Elite.tres",
    "res://Itens/Armaduras/Leves/Capacetes/300072-Véu de Umbra Alta-Normal.tres",
    "res://Itens/Armaduras/Leves/Capacetes/300073-Véu de Umbra Alta-Elite.tres",
    "res://Itens/Armaduras/Leves/Capacetes/300084-Véu do Juramento Antigo-Normal.tres",
    "res://Itens/Armaduras/Leves/Capacetes/300085-Véu do Juramento Antigo-Elite.tres",
    "res://Itens/Armaduras/Leves/Capacetes/300096-Véu de Aço Estelar-Normal.tres",
    "res://Itens/Armaduras/Leves/Capacetes/300097-Véu de Aço Estelar-Elite.tres",
    "res://Itens/Armaduras/Leves/Capacetes/300108-Véu do Eclipse de Mitthara-Normal.tres",
    "res://Itens/Armaduras/Leves/Capacetes/300109-Véu do Eclipse de Mitthara-Elite.tres",
    "res://Itens/Armaduras/Leves/Capacetes/300120-Véu da Ascensão-Normal.tres",
    "res://Itens/Armaduras/Leves/Capacetes/300121-Véu da Ascensão-Elite.tres",
    "res://Itens/Armaduras/Leves/Cintos/300010-Faixa do Despertar-Normal.tres",
    "res://Itens/Armaduras/Leves/Cintos/300011-Faixa do Despertar-Elite.tres",
    "res://Itens/Armaduras/Leves/Cintos/300022-Faixa de Bruma Baixa-Normal.tres",
    "res://Itens/Armaduras/Leves/Cintos/300023-Faixa de Bruma Baixa-Elite.tres",
    "res://Itens/Armaduras/Leves/Cintos/300034-Faixa de Valebosque-Normal.tres",
    "res://Itens/Armaduras/Leves/Cintos/300035-Faixa de Valebosque-Elite.tres",
    "res://Itens/Armaduras/Leves/Cintos/300046-Faixa da Vigília Cinzenta-Normal.tres",
    "res://Itens/Armaduras/Leves/Cintos/300047-Faixa da Vigília Cinzenta-Elite.tres",
    "res://Itens/Armaduras/Leves/Cintos/300058-Faixa de Pedraforte-Normal.tres",
    "res://Itens/Armaduras/Leves/Cintos/300059-Faixa de Pedraforte-Elite.tres",
    "res://Itens/Armaduras/Leves/Cintos/300070-Faixa da Aurora Partida-Normal.tres",
    "res://Itens/Armaduras/Leves/Cintos/300071-Faixa da Aurora Partida-Elite.tres",
    "res://Itens/Armaduras/Leves/Cintos/300082-Faixa de Umbra Alta-Normal.tres",
    "res://Itens/Armaduras/Leves/Cintos/300083-Faixa de Umbra Alta-Elite.tres",
    "res://Itens/Armaduras/Leves/Cintos/300094-Faixa do Juramento Antigo-Normal.tres",
    "res://Itens/Armaduras/Leves/Cintos/300095-Faixa do Juramento Antigo-Elite.tres",
    "res://Itens/Armaduras/Leves/Cintos/300106-Faixa de Aço Estelar-Normal.tres",
    "res://Itens/Armaduras/Leves/Cintos/300107-Faixa de Aço Estelar-Elite.tres",
    "res://Itens/Armaduras/Leves/Cintos/300118-Faixa do Eclipse de Mitthara-Normal.tres",
    "res://Itens/Armaduras/Leves/Cintos/300119-Faixa do Eclipse de Mitthara-Elite.tres",
    "res://Itens/Armaduras/Leves/Cintos/300130-Faixa da Ascensão-Normal.tres",
    "res://Itens/Armaduras/Leves/Cintos/300131-Faixa da Ascensão-Elite.tres",
    "res://Itens/Armaduras/Leves/Luvas/300006-Luvas do Despertar-Normal.tres",
    "res://Itens/Armaduras/Leves/Luvas/300007-Luvas do Despertar-Elite.tres",
    "res://Itens/Armaduras/Leves/Luvas/300018-Luvas de Bruma Baixa-Normal.tres",
    "res://Itens/Armaduras/Leves/Luvas/300019-Luvas de Bruma Baixa-Elite.tres",
    "res://Itens/Armaduras/Leves/Luvas/300030-Luvas de Valebosque-Normal.tres",
    "res://Itens/Armaduras/Leves/Luvas/300031-Luvas de Valebosque-Elite.tres",
    "res://Itens/Armaduras/Leves/Luvas/300042-Luvas da Vigília Cinzenta-Normal.tres",
    "res://Itens/Armaduras/Leves/Luvas/300043-Luvas da Vigília Cinzenta-Elite.tres",
    "res://Itens/Armaduras/Leves/Luvas/300054-Luvas de Pedraforte-Normal.tres",
    "res://Itens/Armaduras/Leves/Luvas/300055-Luvas de Pedraforte-Elite.tres",
    "res://Itens/Armaduras/Leves/Luvas/300066-Luvas da Aurora Partida-Normal.tres",
    "res://Itens/Armaduras/Leves/Luvas/300067-Luvas da Aurora Partida-Elite.tres",
    "res://Itens/Armaduras/Leves/Luvas/300078-Luvas de Umbra Alta-Normal.tres",
    "res://Itens/Armaduras/Leves/Luvas/300079-Luvas de Umbra Alta-Elite.tres",
    "res://Itens/Armaduras/Leves/Luvas/300090-Luvas do Juramento Antigo-Normal.tres",
    "res://Itens/Armaduras/Leves/Luvas/300091-Luvas do Juramento Antigo-Elite.tres",
    "res://Itens/Armaduras/Leves/Luvas/300102-Luvas de Aço Estelar-Normal.tres",
    "res://Itens/Armaduras/Leves/Luvas/300103-Luvas de Aço Estelar-Elite.tres",
    "res://Itens/Armaduras/Leves/Luvas/300114-Luvas do Eclipse de Mitthara-Normal.tres",
    "res://Itens/Armaduras/Leves/Luvas/300115-Luvas do Eclipse de Mitthara-Elite.tres",
    "res://Itens/Armaduras/Leves/Luvas/300126-Luvas da Ascensão-Normal.tres",
    "res://Itens/Armaduras/Leves/Luvas/300127-Luvas da Ascensão-Elite.tres",
    "res://Itens/Armaduras/Leves/Peitorais/300002-Manto do Despertar-Normal.tres",
    "res://Itens/Armaduras/Leves/Peitorais/300003-Manto do Despertar-Elite.tres",
    "res://Itens/Armaduras/Leves/Peitorais/300014-Manto de Bruma Baixa-Normal.tres",
    "res://Itens/Armaduras/Leves/Peitorais/300015-Manto de Bruma Baixa-Elite.tres",
    "res://Itens/Armaduras/Leves/Peitorais/300026-Manto de Valebosque-Normal.tres",
    "res://Itens/Armaduras/Leves/Peitorais/300027-Manto de Valebosque-Elite.tres",
    "res://Itens/Armaduras/Leves/Peitorais/300038-Manto da Vigília Cinzenta-Normal.tres",
    "res://Itens/Armaduras/Leves/Peitorais/300039-Manto da Vigília Cinzenta-Elite.tres",
    "res://Itens/Armaduras/Leves/Peitorais/300050-Manto de Pedraforte-Normal.tres",
    "res://Itens/Armaduras/Leves/Peitorais/300051-Manto de Pedraforte-Elite.tres",
    "res://Itens/Armaduras/Leves/Peitorais/300062-Manto da Aurora Partida-Normal.tres",
    "res://Itens/Armaduras/Leves/Peitorais/300063-Manto da Aurora Partida-Elite.tres",
    "res://Itens/Armaduras/Leves/Peitorais/300074-Manto de Umbra Alta-Normal.tres",
    "res://Itens/Armaduras/Leves/Peitorais/300075-Manto de Umbra Alta-Elite.tres",
    "res://Itens/Armaduras/Leves/Peitorais/300086-Manto do Juramento Antigo-Normal.tres",
    "res://Itens/Armaduras/Leves/Peitorais/300087-Manto do Juramento Antigo-Elite.tres",
    "res://Itens/Armaduras/Leves/Peitorais/300098-Manto de Aço Estelar-Normal.tres",
    "res://Itens/Armaduras/Leves/Peitorais/300099-Manto de Aço Estelar-Elite.tres",
    "res://Itens/Armaduras/Leves/Peitorais/300110-Manto do Eclipse de Mitthara-Normal.tres",
    "res://Itens/Armaduras/Leves/Peitorais/300111-Manto do Eclipse de Mitthara-Elite.tres",
    "res://Itens/Armaduras/Leves/Peitorais/300122-Manto da Ascensão-Normal.tres",
    "res://Itens/Armaduras/Leves/Peitorais/300123-Manto da Ascensão-Elite.tres",
    "res://Itens/Armaduras/Medias/Botas/300140-Botas do Despertar-Normal.tres",
    "res://Itens/Armaduras/Medias/Botas/300141-Botas do Despertar-Elite.tres",
    "res://Itens/Armaduras/Medias/Botas/300152-Botas de Bruma Baixa-Normal.tres",
    "res://Itens/Armaduras/Medias/Botas/300153-Botas de Bruma Baixa-Elite.tres",
    "res://Itens/Armaduras/Medias/Botas/300164-Botas de Valebosque-Normal.tres",
    "res://Itens/Armaduras/Medias/Botas/300165-Botas de Valebosque-Elite.tres",
    "res://Itens/Armaduras/Medias/Botas/300176-Botas da Vigília Cinzenta-Normal.tres",
    "res://Itens/Armaduras/Medias/Botas/300177-Botas da Vigília Cinzenta-Elite.tres",
    "res://Itens/Armaduras/Medias/Botas/300188-Botas de Pedraforte-Normal.tres",
    "res://Itens/Armaduras/Medias/Botas/300189-Botas de Pedraforte-Elite.tres",
    "res://Itens/Armaduras/Medias/Botas/300200-Botas da Aurora Partida-Normal.tres",
    "res://Itens/Armaduras/Medias/Botas/300201-Botas da Aurora Partida-Elite.tres",
    "res://Itens/Armaduras/Medias/Botas/300212-Botas de Umbra Alta-Normal.tres",
    "res://Itens/Armaduras/Medias/Botas/300213-Botas de Umbra Alta-Elite.tres",
    "res://Itens/Armaduras/Medias/Botas/300224-Botas do Juramento Antigo-Normal.tres",
    "res://Itens/Armaduras/Medias/Botas/300225-Botas do Juramento Antigo-Elite.tres",
    "res://Itens/Armaduras/Medias/Botas/300236-Botas de Aço Estelar-Normal.tres",
    "res://Itens/Armaduras/Medias/Botas/300237-Botas de Aço Estelar-Elite.tres",
    "res://Itens/Armaduras/Medias/Botas/300248-Botas do Eclipse de Mitthara-Normal.tres",
    "res://Itens/Armaduras/Medias/Botas/300249-Botas do Eclipse de Mitthara-Elite.tres",
    "res://Itens/Armaduras/Medias/Botas/300260-Botas da Ascensão-Normal.tres",
    "res://Itens/Armaduras/Medias/Botas/300261-Botas da Ascensão-Elite.tres",
    "res://Itens/Armaduras/Medias/Calcas/300136-Calças do Despertar-Normal.tres",
    "res://Itens/Armaduras/Medias/Calcas/300137-Calças do Despertar-Elite.tres",
    "res://Itens/Armaduras/Medias/Calcas/300148-Calças de Bruma Baixa-Normal.tres",
    "res://Itens/Armaduras/Medias/Calcas/300149-Calças de Bruma Baixa-Elite.tres",
    "res://Itens/Armaduras/Medias/Calcas/300160-Calças de Valebosque-Normal.tres",
    "res://Itens/Armaduras/Medias/Calcas/300161-Calças de Valebosque-Elite.tres",
    "res://Itens/Armaduras/Medias/Calcas/300172-Calças da Vigília Cinzenta-Normal.tres",
    "res://Itens/Armaduras/Medias/Calcas/300173-Calças da Vigília Cinzenta-Elite.tres",
    "res://Itens/Armaduras/Medias/Calcas/300184-Calças de Pedraforte-Normal.tres",
    "res://Itens/Armaduras/Medias/Calcas/300185-Calças de Pedraforte-Elite.tres",
    "res://Itens/Armaduras/Medias/Calcas/300196-Calças da Aurora Partida-Normal.tres",
    "res://Itens/Armaduras/Medias/Calcas/300197-Calças da Aurora Partida-Elite.tres",
    "res://Itens/Armaduras/Medias/Calcas/300208-Calças de Umbra Alta-Normal.tres",
    "res://Itens/Armaduras/Medias/Calcas/300209-Calças de Umbra Alta-Elite.tres",
    "res://Itens/Armaduras/Medias/Calcas/300220-Calças do Juramento Antigo-Normal.tres",
    "res://Itens/Armaduras/Medias/Calcas/300221-Calças do Juramento Antigo-Elite.tres",
    "res://Itens/Armaduras/Medias/Calcas/300232-Calças de Aço Estelar-Normal.tres",
    "res://Itens/Armaduras/Medias/Calcas/300233-Calças de Aço Estelar-Elite.tres",
    "res://Itens/Armaduras/Medias/Calcas/300244-Calças do Eclipse de Mitthara-Normal.tres",
    "res://Itens/Armaduras/Medias/Calcas/300245-Calças do Eclipse de Mitthara-Elite.tres",
    "res://Itens/Armaduras/Medias/Calcas/300256-Calças da Ascensão-Normal.tres",
    "res://Itens/Armaduras/Medias/Calcas/300257-Calças da Ascensão-Elite.tres",
    "res://Itens/Armaduras/Medias/Capacetes/300132-Capuz do Despertar-Normal.tres",
    "res://Itens/Armaduras/Medias/Capacetes/300133-Capuz do Despertar-Elite.tres",
    "res://Itens/Armaduras/Medias/Capacetes/300144-Capuz de Bruma Baixa-Normal.tres",
    "res://Itens/Armaduras/Medias/Capacetes/300145-Capuz de Bruma Baixa-Elite.tres",
    "res://Itens/Armaduras/Medias/Capacetes/300156-Capuz de Valebosque-Normal.tres",
    "res://Itens/Armaduras/Medias/Capacetes/300157-Capuz de Valebosque-Elite.tres",
    "res://Itens/Armaduras/Medias/Capacetes/300168-Capuz da Vigília Cinzenta-Normal.tres",
    "res://Itens/Armaduras/Medias/Capacetes/300169-Capuz da Vigília Cinzenta-Elite.tres",
    "res://Itens/Armaduras/Medias/Capacetes/300180-Capuz de Pedraforte-Normal.tres",
    "res://Itens/Armaduras/Medias/Capacetes/300181-Capuz de Pedraforte-Elite.tres",
    "res://Itens/Armaduras/Medias/Capacetes/300192-Capuz da Aurora Partida-Normal.tres",
    "res://Itens/Armaduras/Medias/Capacetes/300193-Capuz da Aurora Partida-Elite.tres",
    "res://Itens/Armaduras/Medias/Capacetes/300204-Capuz de Umbra Alta-Normal.tres",
    "res://Itens/Armaduras/Medias/Capacetes/300205-Capuz de Umbra Alta-Elite.tres",
    "res://Itens/Armaduras/Medias/Capacetes/300216-Capuz do Juramento Antigo-Normal.tres",
    "res://Itens/Armaduras/Medias/Capacetes/300217-Capuz do Juramento Antigo-Elite.tres",
    "res://Itens/Armaduras/Medias/Capacetes/300228-Capuz de Aço Estelar-Normal.tres",
    "res://Itens/Armaduras/Medias/Capacetes/300229-Capuz de Aço Estelar-Elite.tres",
    "res://Itens/Armaduras/Medias/Capacetes/300240-Capuz do Eclipse de Mitthara-Normal.tres",
    "res://Itens/Armaduras/Medias/Capacetes/300241-Capuz do Eclipse de Mitthara-Elite.tres",
    "res://Itens/Armaduras/Medias/Capacetes/300252-Capuz da Ascensão-Normal.tres",
    "res://Itens/Armaduras/Medias/Capacetes/300253-Capuz da Ascensão-Elite.tres",
    "res://Itens/Armaduras/Medias/Cintos/300142-Cinto do Despertar-Normal.tres",
    "res://Itens/Armaduras/Medias/Cintos/300143-Cinto do Despertar-Elite.tres",
    "res://Itens/Armaduras/Medias/Cintos/300154-Cinto de Bruma Baixa-Normal.tres",
    "res://Itens/Armaduras/Medias/Cintos/300155-Cinto de Bruma Baixa-Elite.tres",
    "res://Itens/Armaduras/Medias/Cintos/300166-Cinto de Valebosque-Normal.tres",
    "res://Itens/Armaduras/Medias/Cintos/300167-Cinto de Valebosque-Elite.tres",
    "res://Itens/Armaduras/Medias/Cintos/300178-Cinto da Vigília Cinzenta-Normal.tres",
    "res://Itens/Armaduras/Medias/Cintos/300179-Cinto da Vigília Cinzenta-Elite.tres",
    "res://Itens/Armaduras/Medias/Cintos/300190-Cinto de Pedraforte-Normal.tres",
    "res://Itens/Armaduras/Medias/Cintos/300191-Cinto de Pedraforte-Elite.tres",
    "res://Itens/Armaduras/Medias/Cintos/300202-Cinto da Aurora Partida-Normal.tres",
    "res://Itens/Armaduras/Medias/Cintos/300203-Cinto da Aurora Partida-Elite.tres",
    "res://Itens/Armaduras/Medias/Cintos/300214-Cinto de Umbra Alta-Normal.tres",
    "res://Itens/Armaduras/Medias/Cintos/300215-Cinto de Umbra Alta-Elite.tres",
    "res://Itens/Armaduras/Medias/Cintos/300226-Cinto do Juramento Antigo-Normal.tres",
    "res://Itens/Armaduras/Medias/Cintos/300227-Cinto do Juramento Antigo-Elite.tres",
    "res://Itens/Armaduras/Medias/Cintos/300238-Cinto de Aço Estelar-Normal.tres",
    "res://Itens/Armaduras/Medias/Cintos/300239-Cinto de Aço Estelar-Elite.tres",
    "res://Itens/Armaduras/Medias/Cintos/300250-Cinto do Eclipse de Mitthara-Normal.tres",
    "res://Itens/Armaduras/Medias/Cintos/300251-Cinto do Eclipse de Mitthara-Elite.tres",
    "res://Itens/Armaduras/Medias/Cintos/300262-Cinto da Ascensão-Normal.tres",
    "res://Itens/Armaduras/Medias/Cintos/300263-Cinto da Ascensão-Elite.tres",
    "res://Itens/Armaduras/Medias/Luvas/300138-Luvas do Despertar-Normal.tres",
    "res://Itens/Armaduras/Medias/Luvas/300139-Luvas do Despertar-Elite.tres",
    "res://Itens/Armaduras/Medias/Luvas/300150-Luvas de Bruma Baixa-Normal.tres",
    "res://Itens/Armaduras/Medias/Luvas/300151-Luvas de Bruma Baixa-Elite.tres",
    "res://Itens/Armaduras/Medias/Luvas/300162-Luvas de Valebosque-Normal.tres",
    "res://Itens/Armaduras/Medias/Luvas/300163-Luvas de Valebosque-Elite.tres",
    "res://Itens/Armaduras/Medias/Luvas/300174-Luvas da Vigília Cinzenta-Normal.tres",
    "res://Itens/Armaduras/Medias/Luvas/300175-Luvas da Vigília Cinzenta-Elite.tres",
    "res://Itens/Armaduras/Medias/Luvas/300186-Luvas de Pedraforte-Normal.tres",
    "res://Itens/Armaduras/Medias/Luvas/300187-Luvas de Pedraforte-Elite.tres",
    "res://Itens/Armaduras/Medias/Luvas/300198-Luvas da Aurora Partida-Normal.tres",
    "res://Itens/Armaduras/Medias/Luvas/300199-Luvas da Aurora Partida-Elite.tres",
    "res://Itens/Armaduras/Medias/Luvas/300210-Luvas de Umbra Alta-Normal.tres",
    "res://Itens/Armaduras/Medias/Luvas/300211-Luvas de Umbra Alta-Elite.tres",
    "res://Itens/Armaduras/Medias/Luvas/300222-Luvas do Juramento Antigo-Normal.tres",
    "res://Itens/Armaduras/Medias/Luvas/300223-Luvas do Juramento Antigo-Elite.tres",
    "res://Itens/Armaduras/Medias/Luvas/300234-Luvas de Aço Estelar-Normal.tres",
    "res://Itens/Armaduras/Medias/Luvas/300235-Luvas de Aço Estelar-Elite.tres",
    "res://Itens/Armaduras/Medias/Luvas/300246-Luvas do Eclipse de Mitthara-Normal.tres",
    "res://Itens/Armaduras/Medias/Luvas/300247-Luvas do Eclipse de Mitthara-Elite.tres",
    "res://Itens/Armaduras/Medias/Luvas/300258-Luvas da Ascensão-Normal.tres",
    "res://Itens/Armaduras/Medias/Luvas/300259-Luvas da Ascensão-Elite.tres",
    "res://Itens/Armaduras/Medias/Peitorais/300134-Gibão do Despertar-Normal.tres",
    "res://Itens/Armaduras/Medias/Peitorais/300135-Gibão do Despertar-Elite.tres",
    "res://Itens/Armaduras/Medias/Peitorais/300146-Gibão de Bruma Baixa-Normal.tres",
    "res://Itens/Armaduras/Medias/Peitorais/300147-Gibão de Bruma Baixa-Elite.tres",
    "res://Itens/Armaduras/Medias/Peitorais/300158-Gibão de Valebosque-Normal.tres",
    "res://Itens/Armaduras/Medias/Peitorais/300159-Gibão de Valebosque-Elite.tres",
    "res://Itens/Armaduras/Medias/Peitorais/300170-Gibão da Vigília Cinzenta-Normal.tres",
    "res://Itens/Armaduras/Medias/Peitorais/300171-Gibão da Vigília Cinzenta-Elite.tres",
    "res://Itens/Armaduras/Medias/Peitorais/300182-Gibão de Pedraforte-Normal.tres",
    "res://Itens/Armaduras/Medias/Peitorais/300183-Gibão de Pedraforte-Elite.tres",
    "res://Itens/Armaduras/Medias/Peitorais/300194-Gibão da Aurora Partida-Normal.tres",
    "res://Itens/Armaduras/Medias/Peitorais/300195-Gibão da Aurora Partida-Elite.tres",
    "res://Itens/Armaduras/Medias/Peitorais/300206-Gibão de Umbra Alta-Normal.tres",
    "res://Itens/Armaduras/Medias/Peitorais/300207-Gibão de Umbra Alta-Elite.tres",
    "res://Itens/Armaduras/Medias/Peitorais/300218-Gibão do Juramento Antigo-Normal.tres",
    "res://Itens/Armaduras/Medias/Peitorais/300219-Gibão do Juramento Antigo-Elite.tres",
    "res://Itens/Armaduras/Medias/Peitorais/300230-Gibão de Aço Estelar-Normal.tres",
    "res://Itens/Armaduras/Medias/Peitorais/300231-Gibão de Aço Estelar-Elite.tres",
    "res://Itens/Armaduras/Medias/Peitorais/300242-Gibão do Eclipse de Mitthara-Normal.tres",
    "res://Itens/Armaduras/Medias/Peitorais/300243-Gibão do Eclipse de Mitthara-Elite.tres",
    "res://Itens/Armaduras/Medias/Peitorais/300254-Gibão da Ascensão-Normal.tres",
    "res://Itens/Armaduras/Medias/Peitorais/300255-Gibão da Ascensão-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Botas/300272-Botas do Despertar-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Botas/300273-Botas do Despertar-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Botas/300284-Botas de Bruma Baixa-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Botas/300285-Botas de Bruma Baixa-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Botas/300296-Botas de Valebosque-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Botas/300297-Botas de Valebosque-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Botas/300308-Botas da Vigília Cinzenta-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Botas/300309-Botas da Vigília Cinzenta-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Botas/300320-Botas de Pedraforte-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Botas/300321-Botas de Pedraforte-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Botas/300332-Botas da Aurora Partida-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Botas/300333-Botas da Aurora Partida-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Botas/300344-Botas de Umbra Alta-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Botas/300345-Botas de Umbra Alta-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Botas/300356-Botas do Juramento Antigo-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Botas/300357-Botas do Juramento Antigo-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Botas/300368-Botas de Aço Estelar-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Botas/300369-Botas de Aço Estelar-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Botas/300380-Botas do Eclipse de Mitthara-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Botas/300381-Botas do Eclipse de Mitthara-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Botas/300392-Botas da Ascensão-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Botas/300393-Botas da Ascensão-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Calcas/300268-Grevas do Despertar-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Calcas/300269-Grevas do Despertar-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Calcas/300280-Grevas de Bruma Baixa-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Calcas/300281-Grevas de Bruma Baixa-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Calcas/300292-Grevas de Valebosque-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Calcas/300293-Grevas de Valebosque-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Calcas/300304-Grevas da Vigília Cinzenta-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Calcas/300305-Grevas da Vigília Cinzenta-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Calcas/300316-Grevas de Pedraforte-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Calcas/300317-Grevas de Pedraforte-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Calcas/300328-Grevas da Aurora Partida-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Calcas/300329-Grevas da Aurora Partida-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Calcas/300340-Grevas de Umbra Alta-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Calcas/300341-Grevas de Umbra Alta-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Calcas/300352-Grevas do Juramento Antigo-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Calcas/300353-Grevas do Juramento Antigo-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Calcas/300364-Grevas de Aço Estelar-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Calcas/300365-Grevas de Aço Estelar-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Calcas/300376-Grevas do Eclipse de Mitthara-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Calcas/300377-Grevas do Eclipse de Mitthara-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Calcas/300388-Grevas da Ascensão-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Calcas/300389-Grevas da Ascensão-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Capacetes/300264-Elmo do Despertar-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Capacetes/300265-Elmo do Despertar-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Capacetes/300276-Elmo de Bruma Baixa-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Capacetes/300277-Elmo de Bruma Baixa-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Capacetes/300288-Elmo de Valebosque-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Capacetes/300289-Elmo de Valebosque-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Capacetes/300300-Elmo da Vigília Cinzenta-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Capacetes/300301-Elmo da Vigília Cinzenta-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Capacetes/300312-Elmo de Pedraforte-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Capacetes/300313-Elmo de Pedraforte-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Capacetes/300324-Elmo da Aurora Partida-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Capacetes/300325-Elmo da Aurora Partida-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Capacetes/300336-Elmo de Umbra Alta-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Capacetes/300337-Elmo de Umbra Alta-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Capacetes/300348-Elmo do Juramento Antigo-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Capacetes/300349-Elmo do Juramento Antigo-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Capacetes/300360-Elmo de Aço Estelar-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Capacetes/300361-Elmo de Aço Estelar-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Capacetes/300372-Elmo do Eclipse de Mitthara-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Capacetes/300373-Elmo do Eclipse de Mitthara-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Capacetes/300384-Elmo da Ascensão-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Capacetes/300385-Elmo da Ascensão-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Cintos/300274-Cinturão do Despertar-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Cintos/300275-Cinturão do Despertar-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Cintos/300286-Cinturão de Bruma Baixa-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Cintos/300287-Cinturão de Bruma Baixa-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Cintos/300298-Cinturão de Valebosque-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Cintos/300299-Cinturão de Valebosque-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Cintos/300310-Cinturão da Vigília Cinzenta-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Cintos/300311-Cinturão da Vigília Cinzenta-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Cintos/300322-Cinturão de Pedraforte-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Cintos/300323-Cinturão de Pedraforte-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Cintos/300334-Cinturão da Aurora Partida-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Cintos/300335-Cinturão da Aurora Partida-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Cintos/300346-Cinturão de Umbra Alta-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Cintos/300347-Cinturão de Umbra Alta-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Cintos/300358-Cinturão do Juramento Antigo-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Cintos/300359-Cinturão do Juramento Antigo-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Cintos/300370-Cinturão de Aço Estelar-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Cintos/300371-Cinturão de Aço Estelar-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Cintos/300382-Cinturão do Eclipse de Mitthara-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Cintos/300383-Cinturão do Eclipse de Mitthara-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Cintos/300394-Cinturão da Ascensão-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Cintos/300395-Cinturão da Ascensão-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Luvas/300270-Manoplas do Despertar-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Luvas/300271-Manoplas do Despertar-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Luvas/300282-Manoplas de Bruma Baixa-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Luvas/300283-Manoplas de Bruma Baixa-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Luvas/300294-Manoplas de Valebosque-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Luvas/300295-Manoplas de Valebosque-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Luvas/300306-Manoplas da Vigília Cinzenta-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Luvas/300307-Manoplas da Vigília Cinzenta-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Luvas/300318-Manoplas de Pedraforte-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Luvas/300319-Manoplas de Pedraforte-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Luvas/300330-Manoplas da Aurora Partida-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Luvas/300331-Manoplas da Aurora Partida-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Luvas/300342-Manoplas de Umbra Alta-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Luvas/300343-Manoplas de Umbra Alta-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Luvas/300354-Manoplas do Juramento Antigo-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Luvas/300355-Manoplas do Juramento Antigo-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Luvas/300366-Manoplas de Aço Estelar-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Luvas/300367-Manoplas de Aço Estelar-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Luvas/300378-Manoplas do Eclipse de Mitthara-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Luvas/300379-Manoplas do Eclipse de Mitthara-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Luvas/300390-Manoplas da Ascensão-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Luvas/300391-Manoplas da Ascensão-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Peitorais/300266-Couraça do Despertar-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Peitorais/300267-Couraça do Despertar-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Peitorais/300278-Couraça de Bruma Baixa-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Peitorais/300279-Couraça de Bruma Baixa-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Peitorais/300290-Couraça de Valebosque-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Peitorais/300291-Couraça de Valebosque-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Peitorais/300302-Couraça da Vigília Cinzenta-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Peitorais/300303-Couraça da Vigília Cinzenta-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Peitorais/300314-Couraça de Pedraforte-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Peitorais/300315-Couraça de Pedraforte-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Peitorais/300326-Couraça da Aurora Partida-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Peitorais/300327-Couraça da Aurora Partida-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Peitorais/300338-Couraça de Umbra Alta-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Peitorais/300339-Couraça de Umbra Alta-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Peitorais/300350-Couraça do Juramento Antigo-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Peitorais/300351-Couraça do Juramento Antigo-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Peitorais/300362-Couraça de Aço Estelar-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Peitorais/300363-Couraça de Aço Estelar-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Peitorais/300374-Couraça do Eclipse de Mitthara-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Peitorais/300375-Couraça do Eclipse de Mitthara-Elite.tres",
    "res://Itens/Armaduras/Pesadas/Peitorais/300386-Couraça da Ascensão-Normal.tres",
    "res://Itens/Armaduras/Pesadas/Peitorais/300387-Couraça da Ascensão-Elite.tres",
    "res://Itens/Armas/Adagas/1011-Adaga do Primeiro Corte-Normal.tres",
    "res://Itens/Armas/Adagas/1012-Adaga do Beco Frio-Normal.tres",
    "res://Itens/Armas/Adagas/1013-Adaga de Ferro Sombrio-Normal.tres",
    "res://Itens/Armas/Adagas/1014-Adaga da Máscara Rachada-Normal.tres",
    "res://Itens/Armas/Adagas/1015-Adaga da Lua Baixa-Normal.tres",
    "res://Itens/Armas/Adagas/1016-Adaga do Executor Cinzento-Normal.tres",
    "res://Itens/Armas/Adagas/1017-Adaga do Predador Noturno-Normal.tres",
    "res://Itens/Armas/Adagas/1018-Adaga de Aço Negro-Normal.tres",
    "res://Itens/Armas/Adagas/1019-Adaga da Meia-Noite-Normal.tres",
    "res://Itens/Armas/Adagas/1020-Adaga Ancestral das Sombras-Normal.tres",
    "res://Itens/Armas/Adagas/1021-Adaga do Assassino Lendário-Normal.tres",
    "res://Itens/Armas/Adagas/11011-Adaga do Primeiro Corte-Elite.tres",
    "res://Itens/Armas/Adagas/11012-Adaga do Beco Frio-Elite.tres",
    "res://Itens/Armas/Adagas/11013-Adaga de Ferro Sombrio-Elite.tres",
    "res://Itens/Armas/Adagas/11014-Adaga da Máscara Rachada-Elite.tres",
    "res://Itens/Armas/Adagas/11015-Adaga da Lua Baixa-Elite.tres",
    "res://Itens/Armas/Adagas/11016-Adaga do Executor Cinzento-Elite.tres",
    "res://Itens/Armas/Adagas/11017-Adaga do Predador Noturno-Elite.tres",
    "res://Itens/Armas/Adagas/11018-Adaga de Aço Negro-Elite.tres",
    "res://Itens/Armas/Adagas/11019-Adaga da Meia-Noite-Elite.tres",
    "res://Itens/Armas/Adagas/11020-Adaga Ancestral das Sombras-Elite.tres",
    "res://Itens/Armas/Adagas/11021-Adaga do Assassino Lendário-Elite.tres",
    "res://Itens/Armas/Arcos/1000-Arco da Primeira Caçada-Normal.tres",
    "res://Itens/Armas/Arcos/1001-Arco do Vento Verde-Normal.tres",
    "res://Itens/Armas/Arcos/1002-Arco de Valebosque-Normal.tres",
    "res://Itens/Armas/Arcos/1003-Arco dos Vigias da Névoa-Normal.tres",
    "res://Itens/Armas/Arcos/1004-Arco de Carvalho Negro-Normal.tres",
    "res://Itens/Armas/Arcos/1005-Arco do Predador Silencioso-Normal.tres",
    "res://Itens/Armas/Arcos/1006-Arco de Chifre de Warg-Normal.tres",
    "res://Itens/Armas/Arcos/1007-Arco dos Olhos de Prata-Normal.tres",
    "res://Itens/Armas/Arcos/1008-Arco Imperial de Mitthara-Normal.tres",
    "res://Itens/Armas/Arcos/1009-Arco Ancestral de Aster-Normal.tres",
    "res://Itens/Armas/Arcos/1010-Arco do Caçador Lendário-Normal.tres",
    "res://Itens/Armas/Arcos/11000-Arco da Primeira Caçada-Elite.tres",
    "res://Itens/Armas/Arcos/11001-Arco do Vento Verde-Elite.tres",
    "res://Itens/Armas/Arcos/11002-Arco de Valebosque-Elite.tres",
    "res://Itens/Armas/Arcos/11003-Arco dos Vigias da Névoa-Elite.tres",
    "res://Itens/Armas/Arcos/11004-Arco de Carvalho Negro-Elite.tres",
    "res://Itens/Armas/Arcos/11005-Arco do Predador Silencioso-Elite.tres",
    "res://Itens/Armas/Arcos/11006-Arco de Chifre de Warg-Elite.tres",
    "res://Itens/Armas/Arcos/11007-Arco dos Olhos de Prata-Elite.tres",
    "res://Itens/Armas/Arcos/11008-Arco Imperial de Mitthara-Elite.tres",
    "res://Itens/Armas/Arcos/11009-Arco Ancestral de Aster-Elite.tres",
    "res://Itens/Armas/Arcos/11010-Arco do Caçador Lendário-Elite.tres",
    "res://Itens/Armas/Cajados/1066-Cajado da Faísca Fraca-Normal.tres",
    "res://Itens/Armas/Cajados/1067-Cajado do Aprendiz Arcano-Normal.tres",
    "res://Itens/Armas/Cajados/1068-Cajado de Carvalho Rúnico-Normal.tres",
    "res://Itens/Armas/Cajados/1069-Cajado da Chama Azul-Normal.tres",
    "res://Itens/Armas/Cajados/1070-Cajado do Erudito Errante-Normal.tres",
    "res://Itens/Armas/Cajados/1071-Cajado do Invocador-Normal.tres",
    "res://Itens/Armas/Cajados/1072-Cajado de Cristal Negro-Normal.tres",
    "res://Itens/Armas/Cajados/1073-Cajado do Mestre Arcano-Normal.tres",
    "res://Itens/Armas/Cajados/1074-Cajado Imperial das Runas-Normal.tres",
    "res://Itens/Armas/Cajados/1075-Cajado Ancestral de Aster-Normal.tres",
    "res://Itens/Armas/Cajados/1076-Cajado do Arquimago Lendário-Normal.tres",
    "res://Itens/Armas/Cajados/11066-Cajado da Faísca Fraca-Elite.tres",
    "res://Itens/Armas/Cajados/11067-Cajado do Aprendiz Arcano-Elite.tres",
    "res://Itens/Armas/Cajados/11068-Cajado de Carvalho Rúnico-Elite.tres",
    "res://Itens/Armas/Cajados/11069-Cajado da Chama Azul-Elite.tres",
    "res://Itens/Armas/Cajados/11070-Cajado do Erudito Errante-Elite.tres",
    "res://Itens/Armas/Cajados/11071-Cajado do Invocador-Elite.tres",
    "res://Itens/Armas/Cajados/11072-Cajado de Cristal Negro-Elite.tres",
    "res://Itens/Armas/Cajados/11073-Cajado do Mestre Arcano-Elite.tres",
    "res://Itens/Armas/Cajados/11074-Cajado Imperial das Runas-Elite.tres",
    "res://Itens/Armas/Cajados/11075-Cajado Ancestral de Aster-Elite.tres",
    "res://Itens/Armas/Cajados/11076-Cajado do Arquimago Lendário-Elite.tres",
    "res://Itens/Armas/Espadas/1044-Espada do Juramento-Normal.tres",
    "res://Itens/Armas/Espadas/1045-Espada de Ferro da Guarda-Normal.tres",
    "res://Itens/Armas/Espadas/1046-Espada do Sentinela-Normal.tres",
    "res://Itens/Armas/Espadas/1047-Espada da Muralha-Normal.tres",
    "res://Itens/Armas/Espadas/1048-Espada do Protetor-Normal.tres",
    "res://Itens/Armas/Espadas/1049-Espada do Defensor Cinzento-Normal.tres",
    "res://Itens/Armas/Espadas/1050-Espada de Aço Negro-Normal.tres",
    "res://Itens/Armas/Espadas/1051-Espada do Campeão da Guarda-Normal.tres",
    "res://Itens/Armas/Espadas/1052-Espada Imperial de Mitthara-Normal.tres",
    "res://Itens/Armas/Espadas/1053-Espada Ancestral do Bastião-Normal.tres",
    "res://Itens/Armas/Espadas/1054-Espada do Guardião Lendário-Normal.tres",
    "res://Itens/Armas/Espadas/11044-Espada do Juramento-Elite.tres",
    "res://Itens/Armas/Espadas/11045-Espada de Ferro da Guarda-Elite.tres",
    "res://Itens/Armas/Espadas/11046-Espada do Sentinela-Elite.tres",
    "res://Itens/Armas/Espadas/11047-Espada da Muralha-Elite.tres",
    "res://Itens/Armas/Espadas/11048-Espada do Protetor-Elite.tres",
    "res://Itens/Armas/Espadas/11049-Espada do Defensor Cinzento-Elite.tres",
    "res://Itens/Armas/Espadas/11050-Espada de Aço Negro-Elite.tres",
    "res://Itens/Armas/Espadas/11051-Espada do Campeão da Guarda-Elite.tres",
    "res://Itens/Armas/Espadas/11052-Espada Imperial de Mitthara-Elite.tres",
    "res://Itens/Armas/Espadas/11053-Espada Ancestral do Bastião-Elite.tres",
    "res://Itens/Armas/Espadas/11054-Espada do Guardião Lendário-Elite.tres",
    "res://Itens/Armas/Machados/1033-Machado Quebra-Tronco-Normal.tres",
    "res://Itens/Armas/Machados/1034-Machado do Sangue Quente-Normal.tres",
    "res://Itens/Armas/Machados/1035-Machado de Ferro Brutal-Normal.tres",
    "res://Itens/Armas/Machados/1036-Machado do Clamor-Normal.tres",
    "res://Itens/Armas/Machados/1037-Machado do Conquistador-Normal.tres",
    "res://Itens/Armas/Machados/1038-Machado Presa-de-Fera-Normal.tres",
    "res://Itens/Armas/Machados/1039-Machado de Aço Negro-Normal.tres",
    "res://Itens/Armas/Machados/1040-Machado do Campeão Rubro-Normal.tres",
    "res://Itens/Armas/Machados/1041-Machado Imperial de Guerra-Normal.tres",
    "res://Itens/Armas/Machados/1042-Machado Ancestral dos Colossos-Normal.tres",
    "res://Itens/Armas/Machados/1043-Machado do Berserker Lendário-Normal.tres",
    "res://Itens/Armas/Machados/11033-Machado Quebra-Tronco-Elite.tres",
    "res://Itens/Armas/Machados/11034-Machado do Sangue Quente-Elite.tres",
    "res://Itens/Armas/Machados/11035-Machado de Ferro Brutal-Elite.tres",
    "res://Itens/Armas/Machados/11036-Machado do Clamor-Elite.tres",
    "res://Itens/Armas/Machados/11037-Machado do Conquistador-Elite.tres",
    "res://Itens/Armas/Machados/11038-Machado Presa-de-Fera-Elite.tres",
    "res://Itens/Armas/Machados/11039-Machado de Aço Negro-Elite.tres",
    "res://Itens/Armas/Machados/11040-Machado do Campeão Rubro-Elite.tres",
    "res://Itens/Armas/Machados/11041-Machado Imperial de Guerra-Elite.tres",
    "res://Itens/Armas/Machados/11042-Machado Ancestral dos Colossos-Elite.tres",
    "res://Itens/Armas/Machados/11043-Machado do Berserker Lendário-Elite.tres",
    "res://Itens/Armas/Martelos/1077-Martelo do Primeiro Voto-Normal.tres",
    "res://Itens/Armas/Martelos/1078-Martelo do Noviço-Normal.tres",
    "res://Itens/Armas/Martelos/1079-Martelo Consagrado-Normal.tres",
    "res://Itens/Armas/Martelos/1080-Martelo da Capela Velha-Normal.tres",
    "res://Itens/Armas/Martelos/1081-Martelo da Luz Serena-Normal.tres",
    "res://Itens/Armas/Martelos/1082-Martelo do Sacerdote Guerreiro-Normal.tres",
    "res://Itens/Armas/Martelos/1083-Martelo de Prata Sagrada-Normal.tres",
    "res://Itens/Armas/Martelos/1084-Martelo do Arcebispo-Normal.tres",
    "res://Itens/Armas/Martelos/1085-Martelo Imperial da Fé-Normal.tres",
    "res://Itens/Armas/Martelos/1086-Martelo Ancestral dos Templos-Normal.tres",
    "res://Itens/Armas/Martelos/1087-Martelo do Sumo Sacerdote-Normal.tres",
    "res://Itens/Armas/Martelos/11077-Martelo do Primeiro Voto-Elite.tres",
    "res://Itens/Armas/Martelos/11078-Martelo do Noviço-Elite.tres",
    "res://Itens/Armas/Martelos/11079-Martelo Consagrado-Elite.tres",
    "res://Itens/Armas/Martelos/11080-Martelo da Capela Velha-Elite.tres",
    "res://Itens/Armas/Martelos/11081-Martelo da Luz Serena-Elite.tres",
    "res://Itens/Armas/Martelos/11082-Martelo do Sacerdote Guerreiro-Elite.tres",
    "res://Itens/Armas/Martelos/11083-Martelo de Prata Sagrada-Elite.tres",
    "res://Itens/Armas/Martelos/11084-Martelo do Arcebispo-Elite.tres",
    "res://Itens/Armas/Martelos/11085-Martelo Imperial da Fé-Elite.tres",
    "res://Itens/Armas/Martelos/11086-Martelo Ancestral dos Templos-Elite.tres",
    "res://Itens/Armas/Martelos/11087-Martelo do Sumo Sacerdote-Elite.tres",
    "res://Itens/Consumiveis/LojinhaGrande.tres",
    "res://Itens/Consumiveis/LojinhaMedia.tres",
    "res://Itens/Consumiveis/LojinhaPequena.tres",
    "res://Itens/Consumiveis/PergaminhoDeCriacaoDeCla.tres",
    "res://Itens/Consumiveis/PergaminhoDoPet.tres",
    "res://Itens/Consumiveis/PergaminhoDoPet5.tres",
    "res://Itens/Consumiveis/PergaminhoResetTalentos.tres",
    "res://Itens/Consumiveis/PergaminhoVip15Dias.tres",
    "res://Itens/Consumiveis/PergaminhoVip30Dias.tres",
    "res://Itens/Consumiveis/PergaminhoVip7Dias.tres",
    "res://Itens/Consumiveis/PergaminhoVipTrial.tres",
    "res://Itens/Consumiveis/PocaoDeMana.tres",
    "res://Itens/Consumiveis/PocaoDeVida.tres",
    "res://Itens/Consumiveis/PoeiraEstelar.tres",
    "res://Itens/Escudos/AdagasSecundarias/1022-Lâmina de Apoio-Normal.tres",
    "res://Itens/Escudos/AdagasSecundarias/1023-Adaga de Parada-Normal.tres",
    "res://Itens/Escudos/AdagasSecundarias/1024-Lâmina do Duelista-Normal.tres",
    "res://Itens/Escudos/AdagasSecundarias/1025-Adaga do Batedor-Normal.tres",
    "res://Itens/Escudos/AdagasSecundarias/1026-Lâmina da Sombra Curta-Normal.tres",
    "res://Itens/Escudos/AdagasSecundarias/1027-Adaga Defletora-Normal.tres",
    "res://Itens/Escudos/AdagasSecundarias/1028-Lâmina do Predador Silencioso-Normal.tres",
    "res://Itens/Escudos/AdagasSecundarias/1029-Adaga de Aço Negro Leve-Normal.tres",
    "res://Itens/Escudos/AdagasSecundarias/1030-Lâmina da Meia-Noite-Normal.tres",
    "res://Itens/Escudos/AdagasSecundarias/1031-Lâmina Ancestral Oculta-Normal.tres",
    "res://Itens/Escudos/AdagasSecundarias/1032-Lâmina do Lendário Assassino-Normal.tres",
    "res://Itens/Escudos/AdagasSecundarias/11022-Lâmina de Apoio-Elite.tres",
    "res://Itens/Escudos/AdagasSecundarias/11023-Adaga de Parada-Elite.tres",
    "res://Itens/Escudos/AdagasSecundarias/11024-Lâmina do Duelista-Elite.tres",
    "res://Itens/Escudos/AdagasSecundarias/11025-Adaga do Batedor-Elite.tres",
    "res://Itens/Escudos/AdagasSecundarias/11026-Lâmina da Sombra Curta-Elite.tres",
    "res://Itens/Escudos/AdagasSecundarias/11027-Adaga Defletora-Elite.tres",
    "res://Itens/Escudos/AdagasSecundarias/11028-Lâmina do Predador Silencioso-Elite.tres",
    "res://Itens/Escudos/AdagasSecundarias/11029-Adaga de Aço Negro Leve-Elite.tres",
    "res://Itens/Escudos/AdagasSecundarias/11030-Lâmina da Meia-Noite-Elite.tres",
    "res://Itens/Escudos/AdagasSecundarias/11031-Lâmina Ancestral Oculta-Elite.tres",
    "res://Itens/Escudos/AdagasSecundarias/11032-Lâmina do Lendário Assassino-Elite.tres",
    "res://Itens/Escudos/EscudosClerigo/1088-Escudo da Primeira Prece-Normal.tres",
    "res://Itens/Escudos/EscudosClerigo/1089-Escudo do Noviço-Normal.tres",
    "res://Itens/Escudos/EscudosClerigo/1090-Escudo Consagrado-Normal.tres",
    "res://Itens/Escudos/EscudosClerigo/1091-Escudo da Capela Velha-Normal.tres",
    "res://Itens/Escudos/EscudosClerigo/1092-Escudo da Luz Serena-Normal.tres",
    "res://Itens/Escudos/EscudosClerigo/1093-Escudo do Sacerdote Guardião-Normal.tres",
    "res://Itens/Escudos/EscudosClerigo/1094-Escudo de Prata Sagrada-Normal.tres",
    "res://Itens/Escudos/EscudosClerigo/1095-Escudo do Arcebispo-Normal.tres",
    "res://Itens/Escudos/EscudosClerigo/1096-Escudo Imperial da Fé-Normal.tres",
    "res://Itens/Escudos/EscudosClerigo/1097-Escudo Ancestral dos Templos-Normal.tres",
    "res://Itens/Escudos/EscudosClerigo/1098-Escudo do Sumo Sacerdote-Normal.tres",
    "res://Itens/Escudos/EscudosClerigo/11088-Escudo da Primeira Prece-Elite.tres",
    "res://Itens/Escudos/EscudosClerigo/11089-Escudo do Noviço-Elite.tres",
    "res://Itens/Escudos/EscudosClerigo/11090-Escudo Consagrado-Elite.tres",
    "res://Itens/Escudos/EscudosClerigo/11091-Escudo da Capela Velha-Elite.tres",
    "res://Itens/Escudos/EscudosClerigo/11092-Escudo da Luz Serena-Elite.tres",
    "res://Itens/Escudos/EscudosClerigo/11093-Escudo do Sacerdote Guardião-Elite.tres",
    "res://Itens/Escudos/EscudosClerigo/11094-Escudo de Prata Sagrada-Elite.tres",
    "res://Itens/Escudos/EscudosClerigo/11095-Escudo do Arcebispo-Elite.tres",
    "res://Itens/Escudos/EscudosClerigo/11096-Escudo Imperial da Fé-Elite.tres",
    "res://Itens/Escudos/EscudosClerigo/11097-Escudo Ancestral dos Templos-Elite.tres",
    "res://Itens/Escudos/EscudosClerigo/11098-Escudo do Sumo Sacerdote-Elite.tres",
    "res://Itens/Escudos/EscudosGuardiao/1055-Escudo de Tábua Ferrada-Normal.tres",
    "res://Itens/Escudos/EscudosGuardiao/1056-Escudo da Guarda Jovem-Normal.tres",
    "res://Itens/Escudos/EscudosGuardiao/1057-Escudo do Sentinela-Normal.tres",
    "res://Itens/Escudos/EscudosGuardiao/1058-Escudo da Muralha Baixa-Normal.tres",
    "res://Itens/Escudos/EscudosGuardiao/1059-Escudo do Protetor-Normal.tres",
    "res://Itens/Escudos/EscudosGuardiao/1060-Escudo do Defensor Cinzento-Normal.tres",
    "res://Itens/Escudos/EscudosGuardiao/1061-Escudo de Aço Negro-Normal.tres",
    "res://Itens/Escudos/EscudosGuardiao/1062-Escudo do Campeão da Guarda-Normal.tres",
    "res://Itens/Escudos/EscudosGuardiao/1063-Escudo Imperial de Mitthara-Normal.tres",
    "res://Itens/Escudos/EscudosGuardiao/1064-Escudo Ancestral do Bastião-Normal.tres",
    "res://Itens/Escudos/EscudosGuardiao/1065-Escudo do Guardião Lendário-Normal.tres",
    "res://Itens/Escudos/EscudosGuardiao/11055-Escudo de Tábua Ferrada-Elite.tres",
    "res://Itens/Escudos/EscudosGuardiao/11056-Escudo da Guarda Jovem-Elite.tres",
    "res://Itens/Escudos/EscudosGuardiao/11057-Escudo do Sentinela-Elite.tres",
    "res://Itens/Escudos/EscudosGuardiao/11058-Escudo da Muralha Baixa-Elite.tres",
    "res://Itens/Escudos/EscudosGuardiao/11059-Escudo do Protetor-Elite.tres",
    "res://Itens/Escudos/EscudosGuardiao/11060-Escudo do Defensor Cinzento-Elite.tres",
    "res://Itens/Escudos/EscudosGuardiao/11061-Escudo de Aço Negro-Elite.tres",
    "res://Itens/Escudos/EscudosGuardiao/11062-Escudo do Campeão da Guarda-Elite.tres",
    "res://Itens/Escudos/EscudosGuardiao/11063-Escudo Imperial de Mitthara-Elite.tres",
    "res://Itens/Escudos/EscudosGuardiao/11064-Escudo Ancestral do Bastião-Elite.tres",
    "res://Itens/Escudos/EscudosGuardiao/11065-Escudo do Guardião Lendário-Elite.tres",
    "res://Itens/Outros/Bolsa6Slots.tres",
    "res://Itens/Outros/Bolsa12Slots.tres",
    "res://Itens/Outros/Bolsa18Slots.tres",
    "res://Itens/Outros/Bolsa24Slots.tres",
    "res://Itens/Outros/BolsaDeCouro.tres",
    "res://Itens/Recursos/Arvore.tres",
    "res://Itens/Recursos/Palmeira.tres",
    };
}

